//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewan.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IOControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IOControlStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ewan.Resources.IOControlStrings", typeof(IOControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        public static string SimulateInput {
            get {
                return ResourceManager.GetString("SimulateInput", resourceCulture);
            }
        }
        
        public static string EdgeDetection {
            get {
                return ResourceManager.GetString("EdgeDetection", resourceCulture);
            }
        }
        
        public static string MappingConfig {
            get {
                return ResourceManager.GetString("MappingConfig", resourceCulture);
            }
        }
        
        public static string OutputTest {
            get {
                return ResourceManager.GetString("OutputTest", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string DigitalInput {
            get {
                return ResourceManager.GetString("DigitalInput", resourceCulture);
            }
        }
        
        public static string DigitalOutput {
            get {
                return ResourceManager.GetString("DigitalOutput", resourceCulture);
            }
        }
        
        public static string Page1 {
            get {
                return ResourceManager.GetString("Page1", resourceCulture);
            }
        }
        
        public static string Page2 {
            get {
                return ResourceManager.GetString("Page2", resourceCulture);
            }
        }
        
        public static string Page3 {
            get {
                return ResourceManager.GetString("Page3", resourceCulture);
            }
        }
        
        public static string Page4 {
            get {
                return ResourceManager.GetString("Page4", resourceCulture);
            }
        }
        
        public static string InputPointsDisplay {
            get {
                return ResourceManager.GetString("InputPointsDisplay", resourceCulture);
            }
        }
        
        public static string OutputPointsDisplay {
            get {
                return ResourceManager.GetString("OutputPointsDisplay", resourceCulture);
            }
        }
        
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        public static string SimulateInputMessage {
            get {
                return ResourceManager.GetString("SimulateInputMessage", resourceCulture);
            }
        }
        
        public static string EdgeDetectionMessage {
            get {
                return ResourceManager.GetString("EdgeDetectionMessage", resourceCulture);
            }
        }
        
        public static string MappingConfigMessage {
            get {
                return ResourceManager.GetString("MappingConfigMessage", resourceCulture);
            }
        }
        
        public static string OutputTestMessage {
            get {
                return ResourceManager.GetString("OutputTestMessage", resourceCulture);
            }
        }
        
        public static string RefreshMessage {
            get {
                return ResourceManager.GetString("RefreshMessage", resourceCulture);
            }
        }
        
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        public static string MappingModeText {
            get {
                return ResourceManager.GetString("MappingModeText", resourceCulture);
            }
        }
        
        public static string RealModeText {
            get {
                return ResourceManager.GetString("RealModeText", resourceCulture);
            }
        }
        
        public static string TestingModeText {
            get {
                return ResourceManager.GetString("TestingModeText", resourceCulture);
            }
        }
        
        public static string OutputTestNormalText {
            get {
                return ResourceManager.GetString("OutputTestNormalText", resourceCulture);
            }
        }
        
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
    }
}