//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewan.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ewan.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Admin user created successfully 的本地化字符串。
        /// </summary>
        public static string AdminUserCreated {
            get {
                return ResourceManager.GetString("AdminUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create admin user 的本地化字符串。
        /// </summary>
        public static string AdminUserCreateFailed {
            get {
                return ResourceManager.GetString("AdminUserCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin user check: {0} 的本地化字符串。
        /// </summary>
        public static string AdminUserLoadCheck {
            get {
                return ResourceManager.GetString("AdminUserLoadCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application is exiting 的本地化字符串。
        /// </summary>
        public static string ApplicationExiting {
            get {
                return ResourceManager.GetString("ApplicationExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application started successfully 的本地化字符串。
        /// </summary>
        public static string ApplicationStarted {
            get {
                return ResourceManager.GetString("ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis added: {0} 的本地化字符串。
        /// </summary>
        public static string AxisAdded {
            get {
                return ResourceManager.GetString("AxisAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add axis: {0} 的本地化字符串。
        /// </summary>
        public static string AxisAddFailed {
            get {
                return ResourceManager.GetString("AxisAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis configuration loaded from: {0} 的本地化字符串。
        /// </summary>
        public static string AxisConfigurationLoaded {
            get {
                return ResourceManager.GetString("AxisConfigurationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load axis configuration: {0} 的本地化字符串。
        /// </summary>
        public static string AxisConfigurationLoadFailed {
            get {
                return ResourceManager.GetString("AxisConfigurationLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis configuration saved to: {0} 的本地化字符串。
        /// </summary>
        public static string AxisConfigurationSaved {
            get {
                return ResourceManager.GetString("AxisConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save axis configuration: {0} 的本地化字符串。
        /// </summary>
        public static string AxisConfigurationSaveFailed {
            get {
                return ResourceManager.GetString("AxisConfigurationSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis connection test failed: {0} 的本地化字符串。
        /// </summary>
        public static string AxisConnectionTestFailed {
            get {
                return ResourceManager.GetString("AxisConnectionTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing axis connection to: {0} 的本地化字符串。
        /// </summary>
        public static string AxisConnectionTesting {
            get {
                return ResourceManager.GetString("AxisConnectionTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis Manager destroy failed: {0} 的本地化字符串。
        /// </summary>
        public static string AxisManagerDestroyFailed {
            get {
                return ResourceManager.GetString("AxisManagerDestroyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis Manager initialization failed: {0} 的本地化字符串。
        /// </summary>
        public static string AxisManagerInitFailed {
            get {
                return ResourceManager.GetString("AxisManagerInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis parameters reset to default values 的本地化字符串。
        /// </summary>
        public static string AxisParametersReset {
            get {
                return ResourceManager.GetString("AxisParametersReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to reset axis parameters: {0} 的本地化字符串。
        /// </summary>
        public static string AxisParametersResetFailed {
            get {
                return ResourceManager.GetString("AxisParametersResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis removed: {0} 的本地化字符串。
        /// </summary>
        public static string AxisRemoved {
            get {
                return ResourceManager.GetString("AxisRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to remove axis: {0} 的本地化字符串。
        /// </summary>
        public static string AxisRemoveFailed {
            get {
                return ResourceManager.GetString("AxisRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Manager destroyed: {0} 的本地化字符串。
        /// </summary>
        public static string BaseManagerDestroyed {
            get {
                return ResourceManager.GetString("BaseManagerDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Manager initialized: {0} 的本地化字符串。
        /// </summary>
        public static string BaseManagerInitialized {
            get {
                return ResourceManager.GetString("BaseManagerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command executed: {0} 的本地化字符串。
        /// </summary>
        public static string CommandExecuted {
            get {
                return ResourceManager.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command received: {0} 的本地化字符串。
        /// </summary>
        public static string CommandReceived {
            get {
                return ResourceManager.GetString("CommandReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file created: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigFileCreated {
            get {
                return ResourceManager.GetString("ConfigFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file loaded: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigFileLoaded {
            get {
                return ResourceManager.GetString("ConfigFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file not found: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file saved: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigFileSaved {
            get {
                return ResourceManager.GetString("ConfigFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration changed: {0} 的本地化字符串。
        /// </summary>
        public static string ConfigurationChanged {
            get {
                return ResourceManager.GetString("ConfigurationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection closed: {0} 的本地化字符串。
        /// </summary>
        public static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection error: {0} 的本地化字符串。
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection established: {0} 的本地化字符串。
        /// </summary>
        public static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture changed to {0} 的本地化字符串。
        /// </summary>
        public static string CultureChanged {
            get {
                return ResourceManager.GetString("CultureChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture Manager destroyed 的本地化字符串。
        /// </summary>
        public static string CultureManagerDestroyed {
            get {
                return ResourceManager.GetString("CultureManagerDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture Manager initialization error: {0} 的本地化字符串。
        /// </summary>
        public static string CultureManagerInitError {
            get {
                return ResourceManager.GetString("CultureManagerInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture Manager initialized successfully 的本地化字符串。
        /// </summary>
        public static string CultureManagerInitialized {
            get {
                return ResourceManager.GetString("CultureManagerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database connected successfully 的本地化字符串。
        /// </summary>
        public static string DatabaseConnected {
            get {
                return ResourceManager.GetString("DatabaseConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database connection error: {0} 的本地化字符串。
        /// </summary>
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data received: {0} bytes 的本地化字符串。
        /// </summary>
        public static string DataReceived {
            get {
                return ResourceManager.GetString("DataReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data sent: {0} bytes 的本地化字符串。
        /// </summary>
        public static string DataSent {
            get {
                return ResourceManager.GetString("DataSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug: {0} 的本地化字符串。
        /// </summary>
        public static string DebugInformation {
            get {
                return ResourceManager.GetString("DebugInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default users created successfully 的本地化字符串。
        /// </summary>
        public static string DefaultUsersCreated {
            get {
                return ResourceManager.GetString("DefaultUsersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory created: {0} 的本地化字符串。
        /// </summary>
        public static string DirectoryCreated {
            get {
                return ResourceManager.GetString("DirectoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal error: {0} 的本地化字符串。
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load file: {0} 的本地化字符串。
        /// </summary>
        public static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found: {0} 的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save file: {0} 的本地化字符串。
        /// </summary>
        public static string FileSaveError {
            get {
                return ResourceManager.GetString("FileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info: {0} 的本地化字符串。
        /// </summary>
        public static string InformationMessage {
            get {
                return ResourceManager.GetString("InformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization completed: {0} 的本地化字符串。
        /// </summary>
        public static string InitializationCompleted {
            get {
                return ResourceManager.GetString("InitializationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization failed: {0} 的本地化字符串。
        /// </summary>
        public static string InitializationFailed {
            get {
                return ResourceManager.GetString("InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization started: {0} 的本地化字符串。
        /// </summary>
        public static string InitializationStarted {
            get {
                return ResourceManager.GetString("InitializationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid username or password 的本地化字符串。
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid culture: {0} 的本地化字符串。
        /// </summary>
        public static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto configuration loaded 的本地化字符串。
        /// </summary>
        public static string IOAutoConfigLoaded {
            get {
                return ResourceManager.GetString("IOAutoConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating default IO configuration 的本地化字符串。
        /// </summary>
        public static string IOConfigCreating {
            get {
                return ResourceManager.GetString("IOConfigCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO configuration file loaded: {0} 的本地化字符串。
        /// </summary>
        public static string IOConfigFileLoaded {
            get {
                return ResourceManager.GetString("IOConfigFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO configuration file not found: {0} 的本地化字符串。
        /// </summary>
        public static string IOConfigFileNotFound {
            get {
                return ResourceManager.GetString("IOConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO configuration saved to: {0} 的本地化字符串。
        /// </summary>
        public static string IOConfigFileSaved {
            get {
                return ResourceManager.GetString("IOConfigFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save IO configuration: {0} 的本地化字符串。
        /// </summary>
        public static string IOConfigFileSaveError {
            get {
                return ResourceManager.GetString("IOConfigFileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO configuration loaded from: {0} 的本地化字符串。
        /// </summary>
        public static string IOConfigurationLoaded {
            get {
                return ResourceManager.GetString("IOConfigurationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO connected: {0} 的本地化字符串。
        /// </summary>
        public static string IOConnected {
            get {
                return ResourceManager.GetString("IOConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO connection error: {0} 的本地化字符串。
        /// </summary>
        public static string IOConnectionError {
            get {
                return ResourceManager.GetString("IOConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO connection failed: {0} 的本地化字符串。
        /// </summary>
        public static string IOConnectionFailed {
            get {
                return ResourceManager.GetString("IOConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default IO mappings created 的本地化字符串。
        /// </summary>
        public static string IODefaultMappingsCreated {
            get {
                return ResourceManager.GetString("IODefaultMappingsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO disconnected 的本地化字符串。
        /// </summary>
        public static string IODisconnected {
            get {
                return ResourceManager.GetString("IODisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO hardware created: {0} 的本地化字符串。
        /// </summary>
        public static string IOHardwareCreated {
            get {
                return ResourceManager.GetString("IOHardwareCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created {0} input mappings 的本地化字符串。
        /// </summary>
        public static string IOInputMappingsCreated {
            get {
                return ResourceManager.GetString("IOInputMappingsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO mapping configuration created successfully 的本地化字符串。
        /// </summary>
        public static string IOMappingCreated {
            get {
                return ResourceManager.GetString("IOMappingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO mapping mode changed to: {0} 的本地化字符串。
        /// </summary>
        public static string IOMappingModeChanged {
            get {
                return ResourceManager.GetString("IOMappingModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO not connected 的本地化字符串。
        /// </summary>
        public static string IONotConnected {
            get {
                return ResourceManager.GetString("IONotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO not initialized 的本地化字符串。
        /// </summary>
        public static string IONotInitialized {
            get {
                return ResourceManager.GetString("IONotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output {0} set to: {1} 的本地化字符串。
        /// </summary>
        public static string IOOutputChanged {
            get {
                return ResourceManager.GetString("IOOutputChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output control error: {0} 的本地化字符串。
        /// </summary>
        public static string IOOutputControlError {
            get {
                return ResourceManager.GetString("IOOutputControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created {0} output mappings 的本地化字符串。
        /// </summary>
        public static string IOOutputMappingsCreated {
            get {
                return ResourceManager.GetString("IOOutputMappingsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error reading {0}: {1} 的本地化字符串。
        /// </summary>
        public static string IOReadError {
            get {
                return ResourceManager.GetString("IOReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to recreate IO: {0} 的本地化字符串。
        /// </summary>
        public static string IORecreationFailed {
            get {
                return ResourceManager.GetString("IORecreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All IO simulations cleared 的本地化字符串。
        /// </summary>
        public static string IOSimulateCleared {
            get {
                return ResourceManager.GetString("IOSimulateCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO simulate error: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string IOSimulateError {
            get {
                return ResourceManager.GetString("IOSimulateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO simulate mode changed: {0} 的本地化字符串。
        /// </summary>
        public static string IOSimulateModeChanged {
            get {
                return ResourceManager.GetString("IOSimulateModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO simulate mode set: {0} = {1} 的本地化字符串。
        /// </summary>
        public static string IOSimulateSet {
            get {
                return ResourceManager.GetString("IOSimulateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO test mode: {0} 的本地化字符串。
        /// </summary>
        public static string IOTestModeChanged {
            get {
                return ResourceManager.GetString("IOTestModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error writing {0}: {1} 的本地化字符串。
        /// </summary>
        public static string IOWriteError {
            get {
                return ResourceManager.GetString("IOWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to write {0} 的本地化字符串。
        /// </summary>
        public static string IOWriteFailed {
            get {
                return ResourceManager.GetString("IOWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully wrote {0} = {1} 的本地化字符串。
        /// </summary>
        public static string IOWriteSuccess {
            get {
                return ResourceManager.GetString("IOWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language changed to {0} 的本地化字符串。
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4net configuration loaded 的本地化字符串。
        /// </summary>
        public static string Log4netConfigLoaded {
            get {
                return ResourceManager.GetString("Log4netConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4net configuration file not found 的本地化字符串。
        /// </summary>
        public static string Log4netConfigNotFound {
            get {
                return ResourceManager.GetString("Log4netConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login error: {0} 的本地化字符串。
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed for user {0} 的本地化字符串。
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed - invalid input 的本地化字符串。
        /// </summary>
        public static string LoginInvalidInput {
            get {
                return ResourceManager.GetString("LoginInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed - incorrect password for user: {0} 的本地化字符串。
        /// </summary>
        public static string LoginPasswordIncorrect {
            get {
                return ResourceManager.GetString("LoginPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} logged in successfully 的本地化字符串。
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login successful for user: {0} 的本地化字符串。
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed - user not found: {0} 的本地化字符串。
        /// </summary>
        public static string LoginUserNotFound {
            get {
                return ResourceManager.GetString("LoginUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} logged out successfully 的本地化字符串。
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainController initialization failed: {0} 的本地化字符串。
        /// </summary>
        public static string MainControllerInitializationFailed {
            get {
                return ResourceManager.GetString("MainControllerInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainController initialized successfully 的本地化字符串。
        /// </summary>
        public static string MainControllerInitialized {
            get {
                return ResourceManager.GetString("MainControllerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main window started 的本地化字符串。
        /// </summary>
        public static string MainWindowStarted {
            get {
                return ResourceManager.GetString("MainWindowStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destroying manager: {0} 的本地化字符串。
        /// </summary>
        public static string ManagerDestroying {
            get {
                return ResourceManager.GetString("ManagerDestroying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager initialization failed: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string ManagerInitializationFailed {
            get {
                return ResourceManager.GetString("ManagerInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager initialized: {0} 的本地化字符串。
        /// </summary>
        public static string ManagerInitialized {
            get {
                return ResourceManager.GetString("ManagerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing manager: {0} 的本地化字符串。
        /// </summary>
        public static string ManagerInitializing {
            get {
                return ResourceManager.GetString("ManagerInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module destroyed: {0} 的本地化字符串。
        /// </summary>
        public static string ModuleDestroyed {
            get {
                return ResourceManager.GetString("ModuleDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module initialization failed: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string ModuleInitializationFailed {
            get {
                return ResourceManager.GetString("ModuleInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module initialized: {0} 的本地化字符串。
        /// </summary>
        public static string ModuleInitialized {
            get {
                return ResourceManager.GetString("ModuleInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module run error: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string ModuleRunError {
            get {
                return ResourceManager.GetString("ModuleRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message manager process error: {0} 的本地化字符串。
        /// </summary>
        public static string MsgManagerProcessError {
            get {
                return ResourceManager.GetString("MsgManagerProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message queue is full, dropping message 的本地化字符串。
        /// </summary>
        public static string MsgManagerQueueFull {
            get {
                return ResourceManager.GetString("MsgManagerQueueFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed successfully 的本地化字符串。
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed: {0} 的本地化字符串。
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password field cannot be empty 的本地化字符串。
        /// </summary>
        public static string PasswordFieldEmpty {
            get {
                return ResourceManager.GetString("PasswordFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission check failed: User not authenticated for {0}.{1} 的本地化字符串。
        /// </summary>
        public static string PermissionCheckNotAuthenticated {
            get {
                return ResourceManager.GetString("PermissionCheckNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission check for {0}: {1}.{2} - {3} 的本地化字符串。
        /// </summary>
        public static string PermissionCheckResult {
            get {
                return ResourceManager.GetString("PermissionCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission denied: {0} 的本地化字符串。
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission granted: {0} 的本地化字符串。
        /// </summary>
        public static string PermissionGranted {
            get {
                return ResourceManager.GetString("PermissionGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission not found: {0} 的本地化字符串。
        /// </summary>
        public static string PermissionNotFound {
            get {
                return ResourceManager.GetString("PermissionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permissions saved successfully 的本地化字符串。
        /// </summary>
        public static string PermissionsSaved {
            get {
                return ResourceManager.GetString("PermissionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save permissions: {0} 的本地化字符串。
        /// </summary>
        public static string PermissionsSaveError {
            get {
                return ResourceManager.GetString("PermissionsSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing complete 的本地化字符串。
        /// </summary>
        public static string ProcessingComplete {
            get {
                return ResourceManager.GetString("ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing completed: {0} 的本地化字符串。
        /// </summary>
        public static string ProcessingCompleted {
            get {
                return ResourceManager.GetString("ProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing error: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing started: {0} 的本地化字符串。
        /// </summary>
        public static string ProcessingStarted {
            get {
                return ResourceManager.GetString("ProcessingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role assigned: {0} to {1} 的本地化字符串。
        /// </summary>
        public static string RoleAssigned {
            get {
                return ResourceManager.GetString("RoleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role not found: {0} 的本地化字符串。
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role removed: {0} from {1} 的本地化字符串。
        /// </summary>
        public static string RoleRemoved {
            get {
                return ResourceManager.GetString("RoleRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save language error: {0} 的本地化字符串。
        /// </summary>
        public static string SaveLanguageError {
            get {
                return ResourceManager.GetString("SaveLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security Manager destroyed 的本地化字符串。
        /// </summary>
        public static string SecurityManagerDestroyed {
            get {
                return ResourceManager.GetString("SecurityManagerDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security Manager initialized successfully 的本地化字符串。
        /// </summary>
        public static string SecurityManagerInitialized {
            get {
                return ResourceManager.GetString("SecurityManagerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service error: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service started: {0} 的本地化字符串。
        /// </summary>
        public static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service stopped: {0} 的本地化字符串。
        /// </summary>
        public static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings loaded successfully 的本地化字符串。
        /// </summary>
        public static string SettingsLoaded {
            get {
                return ResourceManager.GetString("SettingsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load settings: {0} 的本地化字符串。
        /// </summary>
        public static string SettingsLoadError {
            get {
                return ResourceManager.GetString("SettingsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved successfully 的本地化字符串。
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save settings: {0} 的本地化字符串。
        /// </summary>
        public static string SettingsSaveError {
            get {
                return ResourceManager.GetString("SettingsSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream error: {0} - {1} 的本地化字符串。
        /// </summary>
        public static string StreamError {
            get {
                return ResourceManager.GetString("StreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream process started 的本地化字符串。
        /// </summary>
        public static string StreamProcessStarted {
            get {
                return ResourceManager.GetString("StreamProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream process stopped 的本地化字符串。
        /// </summary>
        public static string StreamProcessStopped {
            get {
                return ResourceManager.GetString("StreamProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream runner modules initialized: {0} 的本地化字符串。
        /// </summary>
        public static string StreamRunnerModulesInitialized {
            get {
                return ResourceManager.GetString("StreamRunnerModulesInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream started: {0} 的本地化字符串。
        /// </summary>
        public static string StreamStarted {
            get {
                return ResourceManager.GetString("StreamStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting stream: {0} 的本地化字符串。
        /// </summary>
        public static string StreamStarting {
            get {
                return ResourceManager.GetString("StreamStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream stopped: {0} 的本地化字符串。
        /// </summary>
        public static string StreamStopped {
            get {
                return ResourceManager.GetString("StreamStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping stream: {0} 的本地化字符串。
        /// </summary>
        public static string StreamStopping {
            get {
                return ResourceManager.GetString("StreamStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System initialized successfully 的本地化字符串。
        /// </summary>
        public static string SystemInitialized {
            get {
                return ResourceManager.GetString("SystemInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System shutdown initiated 的本地化字符串。
        /// </summary>
        public static string SystemShutdown {
            get {
                return ResourceManager.GetString("SystemShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System startup completed 的本地化字符串。
        /// </summary>
        public static string SystemStartup {
            get {
                return ResourceManager.GetString("SystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System status: Normal 的本地化字符串。
        /// </summary>
        public static string SystemStatusNormal {
            get {
                return ResourceManager.GetString("SystemStatusNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test log button clicked 的本地化字符串。
        /// </summary>
        public static string TestLogClicked {
            get {
                return ResourceManager.GetString("TestLogClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type loaded: {0} 的本地化字符串。
        /// </summary>
        public static string TypeLoaded {
            get {
                return ResourceManager.GetString("TypeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User already exists: {0} 的本地化字符串。
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User authenticated: {0} 的本地化字符串。
        /// </summary>
        public static string UserAuthenticated {
            get {
                return ResourceManager.GetString("UserAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User created: {0} 的本地化字符串。
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} is exiting the application 的本地化字符串。
        /// </summary>
        public static string UserExiting {
            get {
                return ResourceManager.GetString("UserExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User logged out: {0} 的本地化字符串。
        /// </summary>
        public static string UserLoggedOut {
            get {
                return ResourceManager.GetString("UserLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username field cannot be empty 的本地化字符串。
        /// </summary>
        public static string UsernameFieldEmpty {
            get {
                return ResourceManager.GetString("UsernameFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User not found: {0} 的本地化字符串。
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} users 的本地化字符串。
        /// </summary>
        public static string UsersLoaded {
            get {
                return ResourceManager.GetString("UsersLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load users: {0} 的本地化字符串。
        /// </summary>
        public static string UsersLoadError {
            get {
                return ResourceManager.GetString("UsersLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users saved successfully 的本地化字符串。
        /// </summary>
        public static string UsersSaved {
            get {
                return ResourceManager.GetString("UsersSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save users: {0} 的本地化字符串。
        /// </summary>
        public static string UsersSaveError {
            get {
                return ResourceManager.GetString("UsersSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation error: {0} 的本地化字符串。
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation successful 的本地化字符串。
        /// </summary>
        public static string ValidationSuccess {
            get {
                return ResourceManager.GetString("ValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewModelLocator configured 的本地化字符串。
        /// </summary>
        public static string ViewModelLocatorConfigured {
            get {
                return ResourceManager.GetString("ViewModelLocatorConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: {0} 的本地化字符串。
        /// </summary>
        public static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
    }
}
