//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewan.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ewan.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Base manager {0} destroyed 的本地化字符串。
        /// </summary>
        public static string BaseManagerDestroyed {
            get {
                return ResourceManager.GetString("BaseManagerDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base manager {0} initialized 的本地化字符串。
        /// </summary>
        public static string BaseManagerInitialized {
            get {
                return ResourceManager.GetString("BaseManagerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture changed to: {0} 的本地化字符串。
        /// </summary>
        public static string CultureChanged {
            get {
                return ResourceManager.GetString("CultureChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture manager initialization error: {0} 的本地化字符串。
        /// </summary>
        public static string CultureManagerInitError {
            get {
                return ResourceManager.GetString("CultureManagerInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database connection failed: {0} 的本地化字符串。
        /// </summary>
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid culture: {0}, error: {1} 的本地化字符串。
        /// </summary>
        public static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4net configuration loaded 的本地化字符串。
        /// </summary>
        public static string Log4NetConfigLoaded {
            get {
                return ResourceManager.GetString("Log4NetConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4net configuration not found 的本地化字符串。
        /// </summary>
        public static string Log4NetConfigNotFound {
            get {
                return ResourceManager.GetString("Log4NetConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main controller initialization failed 的本地化字符串。
        /// </summary>
        public static string MainControllerInitializationFailed {
            get {
                return ResourceManager.GetString("MainControllerInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main controller initialized 的本地化字符串。
        /// </summary>
        public static string MainControllerInitialized {
            get {
                return ResourceManager.GetString("MainControllerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main window started 的本地化字符串。
        /// </summary>
        public static string MainWindowStarted {
            get {
                return ResourceManager.GetString("MainWindowStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message manager processing error: {0} 的本地化字符串。
        /// </summary>
        public static string MsgManagerProcessError {
            get {
                return ResourceManager.GetString("MsgManagerProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message queue is full 的本地化字符串。
        /// </summary>
        public static string MsgManagerQueueFull {
            get {
                return ResourceManager.GetString("MsgManagerQueueFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing completed successfully in {0} seconds 的本地化字符串。
        /// </summary>
        public static string ProcessingComplete {
            get {
                return ResourceManager.GetString("ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save language setting error: {0} 的本地化字符串。
        /// </summary>
        public static string SaveLanguageError {
            get {
                return ResourceManager.GetString("SaveLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream runner modules initialized 的本地化字符串。
        /// </summary>
        public static string StreamRunnerModulesInitialized {
            get {
                return ResourceManager.GetString("StreamRunnerModulesInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System status: Normal operation 的本地化字符串。
        /// </summary>
        public static string SystemStatusNormal {
            get {
                return ResourceManager.GetString("SystemStatusNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test log button clicked - Testing internationalization 的本地化字符串。
        /// </summary>
        public static string TestLogClicked {
            get {
                return ResourceManager.GetString("TestLogClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View model locator configured 的本地化字符串。
        /// </summary>
        public static string ViewModelLocatorConfigured {
            get {
                return ResourceManager.GetString("ViewModelLocatorConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System initialized successfully 的本地化字符串。
        /// </summary>
        public static string SystemInitialized {
            get {
                return ResourceManager.GetString("SystemInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database connected successfully 的本地化字符串。
        /// </summary>
        public static string DatabaseConnected {
            get {
                return ResourceManager.GetString("DatabaseConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security manager initialized successfully 的本地化字符串。
        /// </summary>
        public static string SecurityManagerInitialized {
            get {
                return ResourceManager.GetString("SecurityManagerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} login successful 的本地化字符串。
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed: Invalid username or password input 的本地化字符串。
        /// </summary>
        public static string LoginInvalidInput {
            get {
                return ResourceManager.GetString("LoginInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed: User {0} not found or inactive 的本地化字符串。
        /// </summary>
        public static string LoginUserNotFound {
            get {
                return ResourceManager.GetString("LoginUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed: Incorrect password for user {0} 的本地化字符串。
        /// </summary>
        public static string LoginPasswordIncorrect {
            get {
                return ResourceManager.GetString("LoginPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} logged out successfully 的本地化字符串。
        /// </summary>
        public static string UserLoggedOut {
            get {
                return ResourceManager.GetString("UserLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User creation failed: User {0} already exists 的本地化字符串。
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} created successfully 的本地化字符串。
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default users created successfully 的本地化字符串。
        /// </summary>
        public static string DefaultUsersCreated {
            get {
                return ResourceManager.GetString("DefaultUsersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded {0} users from storage 的本地化字符串。
        /// </summary>
        public static string UsersLoaded {
            get {
                return ResourceManager.GetString("UsersLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load user data: {0} 的本地化字符串。
        /// </summary>
        public static string UsersLoadError {
            get {
                return ResourceManager.GetString("UsersLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save user data: {0} 的本地化字符串。
        /// </summary>
        public static string UsersSaveError {
            get {
                return ResourceManager.GetString("UsersSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login error occurred: {0} 的本地化字符串。
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4net configuration loaded 的本地化字符串。
        /// </summary>
        public static string Log4netConfigLoaded {
            get {
                return ResourceManager.GetString("Log4netConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4net configuration not found 的本地化字符串。
        /// </summary>
        public static string Log4netConfigNotFound {
            get {
                return ResourceManager.GetString("Log4netConfigNotFound", resourceCulture);
            }
        }
    }
}
