//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewan.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ewan.Resources.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Scroll 的本地化字符串。
        /// </summary>
        public static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Logs 的本地化字符串。
        /// </summary>
        public static string ClearLogs {
            get {
                return ResourceManager.GetString("ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Logs 的本地化字符串。
        /// </summary>
        public static string ClearMenuText {
            get {
                return ResourceManager.GetString("ClearMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy All Logs 的本地化字符串。
        /// </summary>
        public static string CopyAllLogs {
            get {
                return ResourceManager.GetString("CopyAllLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to copy: {0} 的本地化字符串。
        /// </summary>
        public static string CopyFailedMessage {
            get {
                return ResourceManager.GetString("CopyFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Selected 的本地化字符串。
        /// </summary>
        public static string CopySelected {
            get {
                return ResourceManager.GetString("CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Successful 的本地化字符串。
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied {0} log entries to clipboard 的本地化字符串。
        /// </summary>
        public static string CopySuccessMessage {
            get {
                return ResourceManager.GetString("CopySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Logs 的本地化字符串。
        /// </summary>
        public static string ExportLogs {
            get {
                return ResourceManager.GetString("ExportLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export logs: {0} 的本地化字符串。
        /// </summary>
        public static string ExportFailedMessage {
            get {
                return ResourceManager.GetString("ExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Successful 的本地化字符串。
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs exported to: {0} 的本地化字符串。
        /// </summary>
        public static string ExportSuccessMessage {
            get {
                return ResourceManager.GetString("ExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text files (*.txt)|*.txt|CSV files (*.csv)|*.csv|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string LogExportFilter {
            get {
                return ResourceManager.GetString("LogExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogExport_{0} 的本地化字符串。
        /// </summary>
        public static string LogExportFileName {
            get {
                return ResourceManager.GetString("LogExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}	{1}	{2} 的本地化字符串。
        /// </summary>
        public static string LogExportHeader {
            get {
                return ResourceManager.GetString("LogExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Lines: 的本地化字符串。
        /// </summary>
        public static string MaxLines {
            get {
                return ResourceManager.GetString("MaxLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
    }
}