//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionConfigStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionConfigStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ewan.Resources.PermissionConfigStrings", typeof(PermissionConfigStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRoleButton {
            get {
                return ResourceManager.GetString("AddRoleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role feature is under development....
        /// </summary>
        public static string AddRoleFeatureDevelopment {
            get {
                return ResourceManager.GetString("AddRoleFeatureDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &amp; Restore.
        /// </summary>
        public static string BackupRestore {
            get {
                return ResourceManager.GetString("BackupRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System backup and restore.
        /// </summary>
        public static string BackupRestoreDesc {
            get {
                return ResourceManager.GetString("BackupRestoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Control.
        /// </summary>
        public static string CameraControl {
            get {
                return ResourceManager.GetString("CameraControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control camera devices.
        /// </summary>
        public static string CameraControlDesc {
            get {
                return ResourceManager.GetString("CameraControlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Production.
        /// </summary>
        public static string ConfigureProduction {
            get {
                return ResourceManager.GetString("ConfigureProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure production parameters.
        /// </summary>
        public static string ConfigureProductionDesc {
            get {
                return ResourceManager.GetString("ConfigureProductionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete role '{0}'?.
        /// </summary>
        public static string ConfirmDeleteRole {
            get {
                return ResourceManager.GetString("ConfirmDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration: {0}.
        /// </summary>
        public static string CurrentConfig {
            get {
                return ResourceManager.GetString("CurrentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Delete.
        /// </summary>
        public static string DataDelete {
            get {
                return ResourceManager.GetString("DataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete system data.
        /// </summary>
        public static string DataDeleteDesc {
            get {
                return ResourceManager.GetString("DataDeleteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export system data.
        /// </summary>
        public static string DataExportDesc {
            get {
                return ResourceManager.GetString("DataExportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Import.
        /// </summary>
        public static string DataImport {
            get {
                return ResourceManager.GetString("DataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import external data.
        /// </summary>
        public static string DataImportDesc {
            get {
                return ResourceManager.GetString("DataImportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Role.
        /// </summary>
        public static string DeleteRoleButton {
            get {
                return ResourceManager.GetString("DeleteRoleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Control.
        /// </summary>
        public static string DeviceControl {
            get {
                return ResourceManager.GetString("DeviceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string EngineerRole {
            get {
                return ResourceManager.GetString("EngineerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Config.
        /// </summary>
        public static string ExportConfigButton {
            get {
                return ResourceManager.GetString("ExportConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed: {0}.
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration exported successfully!.
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Permission Configuration.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Config.
        /// </summary>
        public static string ImportConfigButton {
            get {
                return ResourceManager.GetString("ImportConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration imported successfully!.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Permission Configuration.
        /// </summary>
        public static string ImportTitle {
            get {
                return ResourceManager.GetString("ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files|*.json|All Files|*.*.
        /// </summary>
        public static string JsonFiles {
            get {
                return ResourceManager.GetString("JsonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Switch.
        /// </summary>
        public static string LanguageSwitch {
            get {
                return ResourceManager.GetString("LanguageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch system language.
        /// </summary>
        public static string LanguageSwitchDesc {
            get {
                return ResourceManager.GetString("LanguageSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Configuration View.
        /// </summary>
        public static string PermissionConfigView {
            get {
                return ResourceManager.GetString("PermissionConfigView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View permission configuration.
        /// </summary>
        public static string PermissionConfigViewDesc {
            get {
                return ResourceManager.GetString("PermissionConfigViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Configuration Control.
        /// </summary>
        public static string PermissionConfigControl {
            get {
                return ResourceManager.GetString("PermissionConfigControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify permission configuration.
        /// </summary>
        public static string PermissionConfigControlDesc {
            get {
                return ResourceManager.GetString("PermissionConfigControlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Machine Control.
        /// </summary>
        public static string MarkingMachineControl {
            get {
                return ResourceManager.GetString("MarkingMachineControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control marking machine devices.
        /// </summary>
        public static string MarkingMachineControlDesc {
            get {
                return ResourceManager.GetString("MarkingMachineControlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string OperatorRole {
            get {
                return ResourceManager.GetString("OperatorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Configuration.
        /// </summary>
        public static string PermissionConfig {
            get {
                return ResourceManager.GetString("PermissionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure user permissions.
        /// </summary>
        public static string PermissionConfigDesc {
            get {
                return ResourceManager.GetString("PermissionConfigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission configuration has been applied!.
        /// </summary>
        public static string PermissionsApplied {
            get {
                return ResourceManager.GetString("PermissionsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Operation.
        /// </summary>
        public static string ProductionOperation {
            get {
                return ResourceManager.GetString("ProductionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleListTitle {
            get {
                return ResourceManager.GetString("RoleListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role: {0}.
        /// </summary>
        public static string RolePrefix {
            get {
                return ResourceManager.GetString("RolePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission Configuration.
        /// </summary>
        public static string RolePermissionConfiguration {
            get {
                return ResourceManager.GetString("RolePermissionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed: {0}.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Production.
        /// </summary>
        public static string StartProduction {
            get {
                return ResourceManager.GetString("StartProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start production process.
        /// </summary>
        public static string StartProductionDesc {
            get {
                return ResourceManager.GetString("StartProductionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Production.
        /// </summary>
        public static string StopProduction {
            get {
                return ResourceManager.GetString("StopProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop production process.
        /// </summary>
        public static string StopProductionDesc {
            get {
                return ResourceManager.GetString("StopProductionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch User.
        /// </summary>
        public static string SwitchUser {
            get {
                return ResourceManager.GetString("SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to other user accounts.
        /// </summary>
        public static string SwitchUserDesc {
            get {
                return ResourceManager.GetString("SwitchUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Management.
        /// </summary>
        public static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access and modify system settings.
        /// </summary>
        public static string SystemSettingsDesc {
            get {
                return ResourceManager.GetString("SystemSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Control.
        /// </summary>
        public static string UPSControl {
            get {
                return ResourceManager.GetString("UPSControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control UPS devices.
        /// </summary>
        public static string UPSControlDesc {
            get {
                return ResourceManager.GetString("UPSControlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagePerm {
            get {
                return ResourceManager.GetString("UserManagePerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, edit, delete users.
        /// </summary>
        public static string UserManagePermDesc {
            get {
                return ResourceManager.GetString("UserManagePermDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Special Permissions.
        /// </summary>
        public static string UserSpecialPermissions {
            get {
                return ResourceManager.GetString("UserSpecialPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User special permission configuration.
        /// </summary>
        public static string UserSpecialPermissionsDesc {
            get {
                return ResourceManager.GetString("UserSpecialPermissionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Logs.
        /// </summary>
        public static string ViewLogs {
            get {
                return ResourceManager.GetString("ViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View system logs.
        /// </summary>
        public static string ViewLogsDesc {
            get {
                return ResourceManager.GetString("ViewLogsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure system permissions for different roles and users.
        /// </summary>
        public static string WindowDescription {
            get {
                return ResourceManager.GetString("WindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Configuration.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}