//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewan.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ewan.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Administrator 的本地化字符串。
        /// </summary>
        public static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MarkingMachineFeeder 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current User: {0} 的本地化字符串。
        /// </summary>
        public static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current User: 的本地化字符串。
        /// </summary>
        public static string CurrentUserLabel {
            get {
                return ResourceManager.GetString("CurrentUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engineer 的本地化字符串。
        /// </summary>
        public static string EngineerRole {
            get {
                return ResourceManager.GetString("EngineerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engineer 的本地化字符串。
        /// </summary>
        public static string EngineerUser {
            get {
                return ResourceManager.GetString("EngineerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid username or password 的本地化字符串。
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageMenuHeader {
            get {
                return ResourceManager.GetString("LanguageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during login: {0} 的本地化字符串。
        /// </summary>
        public static string LoginErrorOccurred {
            get {
                return ResourceManager.GetString("LoginErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your login information 的本地化字符串。
        /// </summary>
        public static string LoginHeaderText {
            get {
                return ResourceManager.GetString("LoginHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Login 的本地化字符串。
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MarkingMachineFeeder 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No user logged in 的本地化字符串。
        /// </summary>
        public static string NoUserLoggedIn {
            get {
                return ResourceManager.GetString("NoUserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        public static string OperatorRole {
            get {
                return ResourceManager.GetString("OperatorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        public static string OperatorUser {
            get {
                return ResourceManager.GetString("OperatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Configuration 的本地化字符串。
        /// </summary>
        public static string PermissionConfigMenu {
            get {
                return ResourceManager.GetString("PermissionConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password 的本地化字符串。
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter username 的本地化字符串。
        /// </summary>
        public static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch User 的本地化字符串。
        /// </summary>
        public static string SwitchUserButton {
            get {
                return ResourceManager.GetString("SwitchUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Management 的本地化字符串。
        /// </summary>
        public static string SystemManagementMenu {
            get {
                return ResourceManager.GetString("SystemManagementMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string SystemMenu {
            get {
                return ResourceManager.GetString("SystemMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Log 的本地化字符串。
        /// </summary>
        public static string TestLogButton {
            get {
                return ResourceManager.GetString("TestLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user and enter the corresponding password to login 的本地化字符串。
        /// </summary>
        public static string UserInfoText {
            get {
                return ResourceManager.GetString("UserInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
    }
}
